name: MPT Witness Generator Checks

on:
  merge_group:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'
          paths: '["mpt-witness-generator/**"]'


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Format
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: './mpt-witness-generator'
        gofmt-flags: '-l -d'

    - name: Build
      working-directory: ./mpt-witness-generator
      run: go build -v ./...

    - name: Test
      working-directory: ./mpt-witness-generator
      env:
        NO_GETH: true
      run: go test -v ./...
